### ISSUE TITLE
Fresh-eyes Review

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/geoknife#115]
I tried not to cheat by looking at source code (few users will). 

1. Add this type of example to webdata
`webdata('prism', times=as.POSIXct(c('1990-01-01', '1995-01-01')))`

2. Can you change the webdata link in geoknife so it goes to method instead of class?

3. Maybe call out "slots" as in webdata so it is clear those can be passed as "..."?

4. Make URL an exposed field in webgeom (not clear what URL is set).

...in progress

**Comment by jread-usgs** [comment]
I think I got all these in #118
