### ISSUE TITLE
Add emailComplete and waitUntilFinished to knife?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#117]
should these be slots in `webprocess` (knife argument to `geoknife()`) instead of actual args to `geoknife`?

**Comment by jread-usgs** [comment]
@jiwalker-usgs thoughts?

**Comment by jiwalker-usgs** [comment]
I think it makes sense to attach this to the webprocess.  A user is unlikely to change their email address per cut of the knife.  I think the same applies for waitForComplete, it is really kind of a setting based on the process workflow being used.

**Comment by jread-usgs** [comment]
yeah, makes sense in knife.

**Comment by jread-usgs** [comment]
added `wait` and `email` slots to `knife` and changed the way `...` works in `geoknife()`
