### ISSUE TITLE
geojob should store important metadata, such as job date

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#119]
and more. Suggestion from @aappling-usgs

**Comment by jread-usgs** [comment]
- [ ] dateTime created
 - [ ] geoknife package version
more?

**Comment by jread-usgs** [comment]
use `DescribeProcess` for the WPS to extract the algorithm version

**Comment by jread-usgs** [comment]
I think I will skip the dateTime created because that is in `geojob`'s `xml` slot if there is a process.

**Comment by jiwalker-usgs** [comment]
By the way, you don't necessarily have to do the `DescribeProcess` call if you aren't already.  This is a part of the `GetCapabilities` response under the `ProcessOferings` section.  Look for processVersion as that is the value you want to hold on to.

**Comment by jread-usgs** [comment]
yes, I saw that and was planning on using it. Only problem is that some of the algorithms don't use it which I assume is a no-no on our end. see http://cida.usgs.gov/gdp/process/WebProcessingService?service=WPS&version=1.0.0&request=DescribeProcess&identifier=org.n52.wps.server.r.gridded_bioclim for example...

**Comment by jiwalker-usgs** [comment]
Yeah, our WPS4R algorithms don't have versions, or version="", so we should probably add this to these algorithms @dblodgett-usgs

**Comment by jread-usgs** [comment]
yes. public shaming on that. :-1:

**Comment by jread-usgs** [comment]
added version to most recent PR
