### ISSUE TITLE
job status not changing until error() call?

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/geoknife#121]
I've passed in a bad stencil and/or fabric. The job starts with a warning:

```
> job <- geoknife(stencil, fabric)
Warning message:
In checkAttrNamespaces(getEffectiveNamespaces(node), .attrs, suppressNamespaceWarning) :
  missing namespace definitions for prefix(es) xlink
```

I think, "shoot. better fix that stencil and try again." so i try but can't start a new process:
```
> job <- geoknife(stencil, fabric)
Error in start(geojob) : 
  Cannot start a new geojob until a previous one is completed or is error. See "check(geojob)"
In addition: Warning message:
In checkAttrNamespaces(getEffectiveNamespaces(node), .attrs, suppressNamespaceWarning) :
  missing namespace definitions for prefix(es) xlink
```
I run the above line repeatedly, each time getting the error message.

I check the job status. It's at 'error'. 
```
> error(job)
[1] TRUE
```

And now, magically, I can attempt to run again:
```
> job <- geoknife(stencil, fabric)
Warning message:
In checkAttrNamespaces(getEffectiveNamespaces(node), .attrs, suppressNamespaceWarning) :
  missing namespace definitions for prefix(es) xlink
```

Something about calling error(), check(), etc. seems to actually change the state of the job.

**Comment by jread-usgs** [comment]
@aappling-usgs the warning is a known issue that I am leaving in until I figure out how to fix the namespace warnings (or else I will suppress that specific warning). The locking of the package with a single request is in need of some better logic I'm afraid. Will be looking into that.

**Comment by jread-usgs** [comment]
I think this is covered.
