### ISSUE TITLE
webdata options

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/geoknife#122]
This is a documentation issue. `webdata('prism')` looks awfully nice. i want to do it for some other dataset, e.g. the one at http://cida.usgs.gov/thredds/dodsC/mows/sr.html. How do I reference that one? `webdata('mows/sr')`, `webdata('sr')`, and `webdata('mows')` all fail.

Jordan already knows about this general issue. Jordan writes: "One huge gap in the package right now is the user's ability to know what gridded datasets they can process. I simply won't have that in place before next week, but I know what I need to do to get that in. So, all of the examples are for PRISM. "

**Comment by jread-usgs** [comment]
Going to be pretty nice when that gets implemented... :)

I will need to have a few things taken care of. The query data function #86 and some odds and ends with that.
