### ISSUE TITLE
broken job can't be checked

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/geoknife#123]
I thought I'd try a different data source. I did this:
```{r}
> fabric <- webdata(url="http://cida.usgs.gov/thredds/dodsC/mows/sr")
> stencil <- webgeom("state::CO")
> job <- geoknife(stencil, fabric) #ignore the checkAttrNamespaces warning for now - it's a known issue
Warning message:
In checkAttrNamespaces(getEffectiveNamespaces(node), .attrs, suppressNamespaceWarning) :
  missing namespace definitions for prefix(es) xlink
```

When I went to check the job, I couldn't see the status and got this error instead:
```{r}
> check(job)
Error in match.arg(state, c("none", "ProcessStarted", "Process successful",  : 
  'arg' should be one of “none”, “ProcessStarted”, “Process successful”, “ProcessFailed”, “unknown”
> traceback()
5: stop(gettextf("'arg' should be one of %s", paste(dQuote(choices), 
       collapse = ", ")), domain = NA)
4: match.arg(state, c("none", "ProcessStarted", "Process successful", 
       "ProcessFailed", "unknown"))
3: setJobState(process$status)
2: check(job)
1: check(job)
```

after this, I can't start a new job because I always get this error, no matter how many times I've called check(job) or error(job):
```{r}
Error in start(geojob) : 
  Cannot start a new geojob until a previous one is completed or is error. See "check(geojob)"
```

**Comment by jread-usgs** [comment]
I need to fix that. But in order to be able to start a new one, just restart your R session (it is an environment variable).

**Comment by jread-usgs** [comment]
update: you can do `job <- cancel(job)` or `cancel()` to kill the local job reference. The first one can be helpful because you can do `start(job)` later if you want.

**Comment by aappling-usgs** [comment]
awesome!

**Comment by jread-usgs** [comment]
This should be taken care of now. Because it errors instead of warns, `job` isn't overwritten when it can't be sent off.
