### ISSUE TITLE
segfault bug for linux builds

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#138]
https://travis-ci.org/USGS-R/geoknife/builds/63045728#L1234

**Comment by jiwalker-usgs** [comment]
Looks like a bug in XML?

**Comment by jread-usgs** [comment]
@jiwalker-usgs you get that on your linux boxy?

**Comment by jiwalker-usgs** [comment]
probably, let me try

**Comment by jiwalker-usgs** [comment]
I couldn't reproduce locally, not sure what would be different.
