### ISSUE TITLE
setting two times as chars for POSIX coercion doesn't work

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#149]
`times(fabric) <- c("1985-01-01","1992-01-01")`
fails, but
`times(fabric)[1] <- "1985-01-01"`
and 
`times(fabric)[2] <- "1992-01-01"`
are both valid

**Comment by jread-usgs** [comment]
should be a relatively easy fix if anyone wants to jump in.

**Comment by aappling-usgs** [comment]
Did this already get fixed?
```
> wd <- webdata('prism')
> times(wd) <- c("1985-01-01","1992-01-01")
> times(wd)
[1] "1985-01-01 CST" "1992-01-01 CST"
```
seems to work fine for me

**Comment by jread-usgs** [comment]
yeah, odd. I was wondering why it didn't work in the first place, since it should have coerced anything that could be POSIXct...
Thanks.

**Comment by jread-usgs** [comment]
This might be a creation thing:
```R
webdata('prism', times = c('2001-01-01','2010-01-01'))
```
fails
