### ISSUE TITLE
shorthand for algorithms

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/geoknife#159]
Is there a shorthand way to specify an algorithm, something like `algorithm("weighted stats")`? Looking for something comparable to `webgeom('state::Colorado')`, etc.

If this gets implemented, note the new feature at https://github.com/USGS-R/geoknife/blob/master/vignettes/geoknife.Rmd#query-function-for-webprocess

**Comment by jread-usgs** [comment]
adding this for v1.3.0
