### ISSUE TITLE
dodsReplace not working for nldas (probably gldas too)

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#163]
dods://hydro1.sci.gsfc.nasa.gov/dods/NLDAS_FORA0125_H.002

should be the url for

http://hydro1.sci.gsfc.nasa.gov/dods/NLDAS_FORA0125_H.002

**Comment by jiwalker-usgs** [comment]
I think you should be able to send a HEAD request to these urls and you will get a header that will explain that it is OPeNDAP and can be switched to dods protocol.

**Comment by jread-usgs** [comment]
thx @jiwalker-usgs looks like a better way to do it

**Comment by jiwalker-usgs** [comment]
Not sure if that can be relied upon for all OPeNDAP servers, but I got that tip from John Caron a while back.

**Comment by jread-usgs** [comment]
hmm...not sure if I can reliably pull OPeNDAP info out of this. Here is NLDAS:

httr::headers(httr::HEAD(uri))
$date
[1] "Thu, 03 Sep 2015 13:04:11 GMT"

$server
[1] "Apache"

$`x-frame-options`
[1] "SAMEORIGIN"

$`xdods-server`
[1] "dods/3.2"

$xdap
[1] "3.2"

$`content-description`
[1] "dods_info"

$`last-modified`
[1] "Thu, 03 Sep 2015 05:53:46 GMT"

$`content-length`
[1] "24428"

$`content-type`
[1] "text/html; charset=UTF-8"

$connection
[1] "close"

vs `httr::HEAD("http://cida.usgs.gov/thredds/dodsC/prism")` is a 400

**Comment by jread-usgs** [comment]
this may be reliable after all:

```r
httr::headers(httr::HEAD("http://apdrc.soest.hawaii.edu:80/dods/public_data/satellite_product/GHRSST/ghrsst_global"))$`xdods-server`
```

**Comment by jread-usgs** [comment]
I need to more robustly test this, maybe by looping through the datasets returned by `query('webdata')` and creating a really small job...just not sure how many variations there are.

**Comment by jread-usgs** [comment]
tried this with all the datasets in the catalog (~190 or so) and it worked as expected. Closing with #264
