### ISSUE TITLE
allow masked functions to fall back to default calls

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#197]
e.g. `url` `title` `query` etc

These all operate on geoknife-specific objects, so it should be easy to dispatch to their base (or other) namespace calls when they aren't used on a geoknife object.

:+1: if anyone else thinks this should be a priority.

**Comment by aappling-usgs** [comment]
It's a good idea but doesn't strike me as urgent - users can always fix conflicts with `base::url`, etc. Then again, like you said - should be easy...

**Comment by jread-usgs** [comment]
yep, ok. That's what I was thinking too. I will try to address this *after* all the dust settles.
