### ISSUE TITLE
Look into using the whisker package for xml templating

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#199]
@jiwalker-usgs do you have an example?

**Comment by jiwalker-usgs** [comment]
On internal gitlab, but look at https://gitlab.cr.usgs.gov/dblodgett/derivatives_runner/tree/master/thredds it has template and script.  Slightly complex, but it is basically building up a fancy list.

**Comment by jread-usgs** [comment]
thanks

**Comment by jread-usgs** [comment]
If this works, it would allow us to drop `XML` and pick up `xml2` as a parser for responses

**Comment by jread-usgs** [comment]
Looks like `XML` fails before the post when it does seg fault.

**Comment by jread-usgs** [comment]
Waiting to see if `xml2` is going to add creation of xml, which makes this switch unnecessary https://github.com/hadley/xml2/issues/9

**Comment by jread-usgs** [comment]
I think we should wait for xml2: https://github.com/hadley/xml2/pull/76

**Comment by jread-usgs** [comment]
I kind of want to use whisker for the post body content.

**Comment by jread-usgs** [comment]
@jiwalker-usgs do you have thoughts on `whisker` vs `xml2` for building these? I'd like to move towards one of the two in the next unplanned minor release (1.5.0?) or later.

**Comment by jiwalker-usgs** [comment]
I think whisker is easier to maintain for simple xml documents, but once it gets too complex it is probably time to go with xml2 as a more powerful tool.  I lean towards whisker in this case, but I might be leaving out some complexity in my thinking.

**Comment by dblodgett-usgs** [comment]
Now that I've worked through `xml2` for reads, I think just using `xml2` for writes is going to be a pretty easy refactor. Any argument to switch to whisker if it's easy enough to just switch our `XML` calls to `xml2`?

**Comment by jiwalker-usgs** [comment]
The main argument for whisker is that building xml documents procedurally is not a clear as if the document is separate and values are inserted.  I think building the document in xml2 should be fine though.

**Comment by dblodgett-usgs** [comment]
I'm moving forward with whisker. It's way more simple and not a bad refactor, mostly deleting code. Can you review my work later today?

**Comment by wdwatkins** [comment]
Whisker also isn't bringing in any additional downstream dependencies, so it doesn't seem like a big deal to bring it in.

**Comment by dblodgett-usgs** [comment]
All done in #362
