### ISSUE TITLE
configurable `wait` parameter

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#237]
I think this currently does a 5s sleep and retry on the process state. For jobs that I know are going to be much longer, I would like to be able to set this to ~30s or so (likewise, maybe 1s for short jobs). 

where does this configuration live? in the argument, or in a package variable that you can adjust?

**Comment by jiwalker-usgs** [comment]
Both?  It should be a job specific attribute so it can be changed based on the type of job, but there should be a way to change the default across jobs.  Either expose something in the package environment or use `options()` or something.

**Comment by jread-usgs** [comment]
Yes, I agree. I am working on a solution for both for this, and hopefully a pattern that will make that kind of thing simpler to do the same with other similar things (such as setting verbose=TRUE for all vs a single call).
