### ISSUE TITLE
obscure read only parts of webprocess()

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#243]
such as TIME_START, etc, which are set by values in the fabric. 

Hide this in the show method and then error when a user tries to change this directly.

**Comment by jread-usgs** [comment]
kind of a `read.only` for the inputs

**Comment by jread-usgs** [comment]
but not even a public `read`

**Comment by jread-usgs** [comment]
these are the internal function names in https://github.com/USGS-R/geoknife/blob/master/R/setProcessInputs.R

**Comment by aappling-usgs** [comment]
cool!

**Comment by jread-usgs** [comment]
part of this is done with #246 , but I don't yet `stop()` when a user tries to set these. So still a WIP
