### ISSUE TITLE
return unique options in queries

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/geoknife#278]
``` r
query(webgeom(geom="sample:CONUS_states" , attribute = "STATE_FIPS"), 'values')
```

returns many copies of each value (varies by value).

```
> table(query(webgeom(geom="sample:CONUS_states" , attribute = "STATE_FIPS"), 'values'))
 01  04  05  06  08  09  10  11  12  13  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33 
 19   1   1  29   1   2   1   1 355  24   1   2   2   1   1   2 273 155  37  19 172   3  10   1   1   1   1   1 
 34  35  36  37  38  39  40  41  42  44  45  46  47  48  49  50  51  53  54  55  56 
 18   1  23 151   1   6   1  20   2   7  22   1   1  60   1   1  59  50   1  36   1 
```

how about running `unique()` on the output before returning from `query`?

**Comment by aappling-usgs** [comment]
see #279 for nuance that should be considered before implementing this change.

**Comment by jread-usgs** [comment]
hmm....surprised this didn't work: https://github.com/jread-usgs/geoknife/commit/fc662ee6840efd9ded94b997ac1d4ccbcf2618bf

probably need a better test for this. Or maybe that code was pulled out? will take a closer look

**Comment by jread-usgs** [comment]
I think @dblodgett-usgs changed the feature behind the `sample:CONUS_states`. It no long has the "STATE_FIPS" attribute
```r
query(webgeom(geom="sample:CONUS_states" , attribute = "STATE"), 'values')
 [1] "Alabama"              "Arizona"              "Arkansas"             "California"           "Colorado"             "Connecticut"          "Delaware"             "District of Columbia"
 [9] "Florida"              "Georgia"              "Idaho"                "Illinois"             "Indiana"              "Iowa"                 "Kansas"               "Kentucky"            
[17] "Louisiana"            "Maine"                "Maryland"             "Massachusetts"        "Michigan"             "Minnesota"            "Mississippi"          "Missouri"            
[25] "Montana"              "Nebraska"             "Nevada"               "New Hampshire"        "New Jersey"           "New Mexico"           "New York"             "North Carolina"      
[33] "North Dakota"         "Ohio"                 "Oklahoma"             "Oregon"               "Pennsylvania"         "Rhode Island"         "South Carolina"       "South Dakota"        
[41] "Tennessee"            "Texas"                "Utah"                 "Vermont"              "Virginia"             "Washington"           "West Virginia"        "Wisconsin"           
[49] "Wyoming" 
```
works as expected in v1.3.5

**Comment by jread-usgs** [comment]
this does recreate the issue though:
```r
query(webgeom(geom="sample:US_Counties" , attribute = "STATE_FIPS"), 'values')
```

**Comment by dblodgett-usgs** [comment]
This is fallout from the sample/derivative switch. I can switch to one that does contain STATE_FIPS. Should I do it? Will switch back to `CONUS_States` rather than `CONUS_states`

**Comment by jread-usgs** [comment]
FIPS code is a pretty useful thing to have in there. Your call.

**Comment by dblodgett-usgs** [comment]
Actually, I take that back. This is fallout from switching to the new geoserver. We had different shapefiles in there for sample and derivative namespaces and I eliminated one of them. The problem with the one that does contain FIPS is that it contains many more small polygons than the one that is in there now... I'll look at them and see what I can do.

**Comment by dblodgett-usgs** [comment]
OK, FIPS is now available in the sample:CONUS_states shapefile... just realized I named it FIPS instead of STATE_FIPS, will that be ok?

**Comment by lindsaycarr** [comment]
@scworland-usgs pointed out that this causes the [TS Colin code](https://owi.usgs.gov/blog/ts-colin-precip/) to break. Is it necessary to call unique within the function? I think it's reasonable to do it outside.

```r
  wg_s <- webgeom(geom = 'derivative:US_Counties', attribute = 'STATE')
  wg_c <- webgeom(geom = 'derivative:US_Counties', attribute = 'COUNTY')
  wg_f <- webgeom(geom = 'derivative:US_Counties', attribute = 'FIPS')
  county_info <- data.frame(state = query(wg_s, 'values'), county = query(wg_c, 'values'), 
                            fips = query(wg_f, 'values'), stringsAsFactors = FALSE) %>% 
    unique() 
```

**Comment by aappling-usgs** [comment]
It's convenient to build the data.frame as you have, but I wonder whether it's a valid and guaranteed assumption that those three separate queries will always return parallel values (such that the first element is the first element across all three queries). If not (and even if it did happen to work for TS Colin), I see that as a good additional reason to call unique() within the query. It still makes a lot more sense to me for individual queries to return unduplicated values.

For solving TS Colin, how about fleshing out that data.frame using http://www2.census.gov/geo/docs/reference/codes/files/national_county.txt? I found it on Data.gov at https://catalog.data.gov/dataset/fips-county-code-look-up-tool. Something like this:

```r
library(data.table)
library(dplyr)
library(geoknife)

wg_f <- webgeom(geom = 'derivative:US_Counties', attribute = 'FIPS')

fips_lookup <- fread('http://www2.census.gov/geo/docs/reference/codes/files/national_county.txt', 
                     data.table=FALSE, colClasses = 'character') %>%
  setNames(c('state','stateFIPS','countyFIPS','county','FIPSclass')) %>%
  mutate(fips = paste0(stateFIPS, countyFIPS)) %>%
  select(fips, state, county)

county_info <- data_frame(fips=query(wg_f, 'values')) %>%
  left_join(fips_lookup, by='fips')
```

**Comment by scworland-usgs** [comment]
It would seem ok for the county geom to return values associated with counties, and then let the user subset the data? Otherwise, querying the geom attributes returns column names for a data set that cannot be accessed using `webgeom`. For example, 

```{r}
query(webgeom(geom='sample:Counties'), 'attributes')
```
returns a list of attributes that cannot be accessed as a single data set. So if someone tries to run the [example](https://github.com/USGS-R/geoknife/blob/master/R/02-webgeom-obj.R#L109) from the reference manual, it will return a a data frame with 0 values:

```{r}
counties <- data.frame(STCountyFIPS=query(webgeom(geom='sample:Counties', attribute='STATE,COUNTY,FIPS'), 'values'), stringsAsFactors=FALSE)
```

**Comment by jread-usgs** [comment]
Looking into this...

**Comment by jread-usgs** [comment]
@scworland-usgs I think I understand the issue here, and there are a few things at play:
1) that example that you noted was not updated to reflect the changes in this new version (an unfortunate example of where putting the code in a `\dontrun{}` block bit us). 2) `geoknife` isn't designed to give access to all of the possible querying and filtering options available with a `WFS` (web feature service, which is what the `webgeom`s are). 3) as Alison mentioned above, the example before relied on results being returned in a reliable order from the service that `query` is using; while that works, I don't think it is a safe assumption across all the various servers that could host a `WFS` that `geoknife` could use, so I wouldn't recommend using that pattern. 
Better yet is to do what Alison noted above, which is to specify the FIPS codes based on knowledge of them from elsewhere.

If doing the type of filtering you have above (and that in the example) is an important and common pattern for workflows, we should look into different ways to support it. Let me know if you have thoughts. I'll leave this issue open to capture the conversation.

**Comment by scworland-usgs** [comment]
@jread-usgs Thank you for looking into it. My main confusion came from trying to use the examples in the reference manual as a template for new tasks. I would imagine that filtering using state names or abbreviations is routine, but as you and @aappling-usgs mention, there are other ways to obtain that data. 

My only lingering thought is why not just query a state data set if you only want state information? 

```r
query(webgeom(geom="sample:CONUS_states" , attribute = "STATE"), 'values')
```
I guess that raises another question: what then is the purpose of the `STATE` attribute in the `geom='sample:Counties'` if there is already a state-level geom? Wouldn't they both provide the same information?

**Comment by jread-usgs** [comment]
If you only want data summarized per state, you can use CONUS_states w/ the "STATE" attribute, or you could use Counties and use the "STATE" attribute there. Despite the Counties dataset having many more polygons (those for the counties), they will be aggregated at the state level when using the "STATE" attribute. We need a good vignette that explains this aggregation behavior, as it isn't really captured in the documentation currently.
