### ISSUE TITLE
good way to search counties within state?

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/geoknife#279]
more generally, maybe, is there a way to get values for 2+ attributes at once, ideally in a data.frame?

for example, here i'm trying to list all the available counties within PR.

```
library(geoknife); library(dplyr)
states <- query(webgeom(geom='derivative:US_Counties', attribute='STATE'), 'values')
counties <- query(webgeom(geom='derivative:US_Counties', attribute='COUNTY'), 'values')
sc <- data_frame(states, counties)
filter(sc, states=='PR')
```

i succeed by am depending on `states` and `counties` coming back as vectors of the same length so that i can make my own table. so this won't work if #278 is resolved as requested (i.e., only returning unique values).

i've just discovered one way to return two attributes:

```
scs <- geoknife::query(webgeom(geom='derivative:US_Counties', attribute='STATE,COUNTY'), 'values')
```

which is better because calling `unique()` within `query()` (as in #278) would still work with this method, but worse because I'd have to parse the 'STCounty Name' string now and there's no delimiter between the state code and county name.

**Comment by jread-usgs** [comment]
I don't really have any good advice for this one...Getting too crazy with helpers for these web features makes me think the functionality should exist within a WFS package (or OWS utils), something like https://github.com/rOpenGov/rwfs

**Comment by jread-usgs** [comment]
It would be nice if what you used above for the query worked with setting the values, eg:

```r
wg <- webgeom(geom='derivative:US_Counties', attribute='STATE,COUNTY', values="VANorthampton County")
 Show Traceback
 
 Rerun with Debug
 Error in xpathApply.XMLInternalDocument(doc, path, fun, ..., namespaces = namespaces,  : 
  error evaluating xpath expression //gml:featureMembers/derivative:US_Counties/derivative:STATE,COUNTY/parent::node() XPath error : Undefined namespace prefix
//gml:featureMembers/derivative:US_Counties/derivative:STATE,COUNTY/parent::node()
                                                            ^
XPath error : Invalid expression
//gml:featureMembers/derivative:US_Counties/derivative:STATE,COUNTY/parent::node()
```

**Comment by jread-usgs** [comment]
to be smarter about this, it would make sense for the returned values to come back delimited, such as:
```r
scs <- geoknife::query(webgeom(geom='derivative:US_Counties', attribute='STATE,COUNTY'), 'values')

**Comment by aappling-usgs** [comment]
agreed - delimited return values would open up a world of possibilities for searching and selecting.

**Comment by jread-usgs** [comment]
The query above is no longer supported and I am tempted to make this a `wontfix` because it is more along the lines of wfs filtering/querying tools than within geoknife's scope. 

What do you think @aappling-usgs ?
