### ISSUE TITLE
Migrate away from 'derivative' namespace shapefiles.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/geoknife#292]
Leaving a place holder to start a conversation about migrating away from the derivative shapefiles as hosted by the primary GDP geoserver. The derivative portal has been shut down and I'd like to tidy up the situation as possible.

**Comment by jread-usgs** [comment]
We can point them somewhere else, but those shapes are only in that namespace right? If you are going to shut it down, it would be good to get them elsewhere for a period of overlap so we can get package updates to trickle down the change over a certain period of time @dblodgett-usgs

**Comment by dblodgett-usgs** [comment]
They should all be available in the 'sample' namespace, but we should double check.

**Comment by jread-usgs** [comment]
updating as a v1.4.0 milestone

**Comment by jread-usgs** [comment]
@dblodgett-usgs , I don't see two of the of the three we include by default in the `sample` namespace, unless those are on a different geoserver.
using 
`derivative:Level_III_Ecoregions`
`derivative:wbdhu8_alb_simp`

I am able to switch
`derivative:CONUS_States`
to 
`sample:CONUS_states`

**Comment by dblodgett-usgs** [comment]
I must have missed them. Will switch it up/add them on Monday.

**Comment by jread-usgs** [comment]
OK @dblodgett-usgs let me know when to check

**Comment by dblodgett-usgs** [comment]
I got this started yesterday and stash was down... will check in now and deploy as long as things are up.

**Comment by dblodgett-usgs** [comment]
OK, configuration run on prod: https://cidasddvasgdp.cr.usgs.gov:8444/jenkins/job/gdp-config-geoserver/37/console
