### ISSUE TITLE
non-noded intersection between LINESTRING

### ISSUE THREAD

**Issue by scworland-usgs** [USGS-R/geoknife#310]
I am trying to extract precip data from the prism dataset for every county in the conterminous US using geoknife. 

``` r
# create web data
precip <- webdata(list(
      times = as.POSIXct(c('1970-01-01','2010-12-01')),
      url = 'http://cida.usgs.gov/thredds/dodsC/prism',
      variables = 'ppt'))
```

The county FIPS codes are pulled directly using the `webgeom` argument:

``` r
# load county FIPS
counties=data.frame(fips=query(webgeom(geom='sample:Counties', attribute='FIPS'),'values'),
                    stringsAsFactors = F)
```

Where `counties$fips` is a 3233x1 vector of FIPS values stored as characters. If you try to then run,

``` r
# create webgeom
cnty <- webgeom(geom='sample:Counties', attribute='FIPS', values=counties$fips)

# extract precip data
precip.job <- geoknife(stencil=cnty, fabric=precip, wait = Twait = F, email = 'scworland@usgs.gov')
```

This will cause the following error:

``` r
$status
[1] "Error subsetting gridded data: Grid doesn't intersect bounding box."
```

Which must be caused by counties in AK, HI, and PR that are not included in prism. Ideally, I could just load the states directly with the FIPS codes,

``` r
# try to load county FIPS and states
counties=data.frame(fips=query(webgeom(geom='sample:Counties', attribute='STATE,FIPS'),'values'),
                    stringsAsFactors = F)
```
and subset the counties using `filter(counties, !STATE %in%("AK","HI","PR"))` before creating the webgeom, but the above code (that includes states) returns 0 values? Was `unique` implemented before returning the values like was requested in issue #278 (it looks like it in line 29 [here](https://github.com/USGS-R/geoknife/blob/master/R/query-webgeom.R#L29))?  Something has changed because if you try to run the `county_info` line (4th line of code) of @lindsaycarr [post](https://owi.usgs.gov/blog/ts-colin-precip/) about TS Colin it also runs into issues due to differing lengths. This is not a huge deal, but something to be aware of.

I can get around that by using the `maps` package (does not contain AK, HI, or PR):

``` r
library(maps) 

#load fips from maps package
counties <- county.fips %>%
  mutate(fips = str_pad(fips, 5, pad = "0"))
```
and then run the geoknife code again,

``` r
# create webgeom
cnty <- webgeom(geom='sample:Counties', attribute='FIPS', values=counties$fips)

# extract precip data
precip.job <- geoknife(stencil=cnty, fabric=precip, wait = F, email = 'scworland@usgs.gov')
```

then this returns the following error:

``` r
$status
[1] "General Error: found non-noded intersection between LINESTRING ( 38.179 -121.665, 38.1772 -121.6632 ) and LINESTRING ( 38.1772 -121.6631, 38.1785 -121.6673 ) [ (38.17724482758621, -121.66324482758621, NaN) ]"
```

I have been able to run the script using just a subset of the counties from the `maps` package, something like:

``` r
# create webgeom
cnty <- webgeom(geom='sample:Counties', attribute='FIPS', values=counties$fips[1:10])

# extract precip data
precip.job <- geoknife(stencil=cnty, fabric=precip, wait = F, email = 'scworland@usgs.gov')
```

Any thoughts about why `attribute='STATE,FIPS'` returns zero values, or the last error about non-noded intersections?

**Comment by jread-usgs** [comment]
@scworland-usgs a couple of different solutions here:

1) run the job for all counties in the `sample:Counties` webgeom but set your knife arguments to allow you to complete the process w/o having full overlap of `stencil` on `fabric`. This is done with 
```r
precip <- webdata(list(
    times = as.POSIXct(c('2010-11-01','2010-12-01')),
    url = 'http://cida.usgs.gov/thredds/dodsC/prism',
    variables = 'ppt'))
stencil <- webgeom(geom='sample:Counties', attribute='FIPS')
precip.job <- geoknife(stencil, fabric=precip, email = 'scworland@usgs.gov', REQUIRE_FULL_COVERAGE = FALSE)
```
That fails with the same linestring error you noted above, but it really shouldn't. it is akin to doing this (all states):
```r
state.job <- geoknife('state', fabric=precip, REQUIRE_FULL_COVERAGE = FALSE)
```
which works fine. So, I think there is an error within that counties dataset that is causing the linestring error.

2) Ignoring that error for the time being, what you did with using the fips from `maps` should work. 

The gotcha here is the use of `query` with a quoted comma-delimited set of attributes. I really did not mean for `query` to support that, but somehow it did in an earlier version. `query` is supposed to work with a 1:1 response to the parameter that you put in.

**Comment by jread-usgs** [comment]
That failed linestring you get seems to be on the border of Soloma and Sacremento counties in California. FIPS '06067' and '06095'. Looking into why this would be the case.

**Comment by jread-usgs** [comment]
```r
all.fips <- stringr::str_pad(as.character(maps::county.fips$fips), pad = '0', width = 5)
stencil <- webgeom(geom='sample:Counties', attribute='FIPS', values=all.fips[!all.fips %in% c('06067','06095')])
precip.job <- geoknife(stencil, fabric=precip)
result(precip.job) %>% head
    DateTime     01001     01003    01005     01007     01009    01011     01013    01015     01017    01019     01021
1 2010-11-01 144.75291 173.09598 78.44871 159.68611 128.37404 99.10976 125.96486 85.26627 110.03404 98.15758 156.72102
2 2010-12-01  45.03142  44.98273 55.72893  55.19091  66.77515 54.07807  37.74743 46.76139  51.80393 59.68092  53.19806
      01023     01025     01027    01029     01031    01033     01035     01037     01039     01041     01043    01045
1 126.74500 146.76343 129.62083 93.48400 105.17406 130.4562 139.76558 147.10257 119.99481 121.13152 141.79597 90.83098
2  44.78046  39.03976  47.14156 56.10798  53.32726  55.6245  43.38547  47.30381  41.21043  44.53377  65.64468 56.53288
      01047     01049     01051    01053     01055     01057     01059     01061     01063     01065    01067    01069
...
```

so @scworland-usgs and @dblodgett-usgs I am seeing an issue with one of the two of those counties, which is causing that linestring error.

**Comment by jread-usgs** [comment]
@scworland-usgs this is a GDP geoserver issue and not a `geoknife` issue, so I have created an issue [here](https://github.com/USGS-CIDA/geo-data-portal/issues/244) and am closing this issue. Note `REQUIRE_FULL_COVERAGE = FALSE` for the future. 

I also created #312 because I noticed that creating a stencil based on a subset of a `webgeom` with lots of values is really slow.

**Comment by scworland-usgs** [comment]
great! @jread-usgs and @dblodgett-usgs everything is working now
