### ISSUE TITLE
creating a stencil with a lot of values takes a lot longer than querying for those values

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#312]
Perhaps there is some major slowdown in the WFS filter, but it is really slow compared to `query(wg,'values')`

**Comment by jread-usgs** [comment]
```r
library(geoknife)
stencil <- webgeom(geom='sample:Counties', attribute='FIPS')
ptm <- proc.time()
FIPS <- query(stencil, 'values')
print(proc.time() - ptm)
```
user  system elapsed 
0.410   0.069   **2.163** 

```r
ptm <- proc.time()
values(stencil) <- FIPS
print(proc.time() - ptm)
```
user  system elapsed 
237.404   2.557 **276.195**

**Comment by jread-usgs** [comment]
probably related to #230

**Comment by jread-usgs** [comment]
creating XML in loops is slooooow. #199 would result in this taking seconds.

**Comment by jread-usgs** [comment]
I think this is a `wontfix` until there is some kind of refactor for building xml

**Comment by dblodgett-usgs** [comment]
refactor of building XML doesn't seem to have done much... will investigate a bit more.

**Comment by jread-usgs** [comment]
This would be fast w/ whisker, right?

**Comment by dblodgett-usgs** [comment]
Everything is using whisker now and I get:
```
> library(geoknife)
> stencil <- webgeom(geom='sample:Counties', attribute='FIPS')
> ptm <- proc.time()
> FIPS <- query(stencil, 'values')
> print(proc.time() - ptm)
   user  system elapsed 
  0.343   0.072  14.849 
```
and 
```
> ptm <- proc.time()
> values(stencil) <- FIPS
> print(proc.time() - ptm)
   user  system elapsed 
  2.168   0.310  98.454 
```

Will have to look into what's taking time. I think it may be service calls?

**Comment by dblodgett-usgs** [comment]
I noticed that we are calling the fetchGMLids function twice here: https://github.com/USGS-R/geoknife/blob/master/R/values-webgeom.R#L40 -- that'll cut the time down a bit since that call is ~30 seconds for this example.

**Comment by dblodgett-usgs** [comment]
The 'query(stencil, 'values')' call can't be helped since it's spent almost entirely calling the WFS to get the list of values. 

The second call really isn't necessary if we can pass the GDP the same filter that's created in https://github.com/USGS-R/geoknife/blob/master/R/values-webgeom.R#L52

I'll see how hard it'll be to inject that into the execute XML and if that will even work.

**Comment by dblodgett-usgs** [comment]
Pretty easy. I have it implemented. See #287 for comment.

The values call is now basically instantaneous because we don't need gmlids.
