### ISSUE TITLE
https .gov changeover

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/geoknife#314]
Found these lines with http .gov URLs using https://github.com/wdwatkins/gran_http_gov

HTTPS is supposed be available for everything by the end of December, but may not be yet.

Some of these URLs in .md and other documentation files won't show up on github unless you go to the raw file. Line numbers reference the number in the raw file when opened in a text editor, so the link may not point you to the right spot in some cases if lines are wrapping, etc.

- [x] https://github.com/USGS-R/geoknife/blob/master/DESCRIPTION#L33
- [x] https://github.com/USGS-R/geoknife/blob/master/R/01-webdata-obj.R#L2
- [x] https://github.com/USGS-R/geoknife/blob/master/R/01-webdata-obj.R#L86
- [x] https://github.com/USGS-R/geoknife/blob/master/R/01-webdata-obj.R#L120
- [x] https://github.com/USGS-R/geoknife/blob/master/R/01-webdata-obj.R#L123
- [x] https://github.com/USGS-R/geoknife/blob/master/R/01-webdata-obj.R#L127
- [x] https://github.com/USGS-R/geoknife/blob/master/R/01-webdata-obj.R#L135
- [x] https://github.com/USGS-R/geoknife/blob/master/R/01-webdata-obj.R#L139
- [x] https://github.com/USGS-R/geoknife/blob/master/R/01-webdata-obj.R#L143
- [x] https://github.com/USGS-R/geoknife/blob/master/R/02-webgeom-obj.R#L28
- [x] https://github.com/USGS-R/geoknife/blob/master/R/02-webgeom-obj.R#L121
- [x] https://github.com/USGS-R/geoknife/blob/master/R/06-simplegeom-obj.R#L31
- [x] https://github.com/USGS-R/geoknife/blob/master/README.Rmd#L16
- [x] https://github.com/USGS-R/geoknife/blob/master/README.Rmd#L33
- [x] https://github.com/USGS-R/geoknife/blob/master/README.Rmd#L77
- [x] https://github.com/USGS-R/geoknife/blob/master/README.Rmd#L147
- [ ] https://github.com/USGS-R/geoknife/blob/master/README.md#L5
- [ ] https://github.com/USGS-R/geoknife/blob/master/README.md#L21
- [ ] https://github.com/USGS-R/geoknife/blob/master/README.md#L71
- [ ] https://github.com/USGS-R/geoknife/blob/master/README.md#L90
- [ ] https://github.com/USGS-R/geoknife/blob/master/README.md#L276
- [x] https://github.com/USGS-R/geoknife/blob/master/demo/iclus_categorical.R#L9
- [x] https://github.com/USGS-R/geoknife/blob/master/demo/prism_subset.R#L3
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L127
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L177
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L197
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L205
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L269
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L333
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L348
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L350
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L352
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L354
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L356
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L444
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L477
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L485
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L504
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L553
- [ ] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.html#L566
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.R#L14
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.R#L140
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.R#L212
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.R#L223
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.Rmd#L42
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.Rmd#L292
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.Rmd#L431
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.Rmd#L466
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.Rmd#L477
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.Rmd#L499
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.Rmd#L556
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/doc/geoknife.Rmd#L575
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/extdata/get_attribute_values.xml#L2
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/extdata/multi_poly_post.xml#L1
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/extdata/multi_poly_post.xml#L74
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/extdata/SB_getCapabilities.xml#L1
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/extdata/SB_getCapabilities.xml#L100
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/extdata/SB_getCapabilities.xml#L114
- [x] https://github.com/USGS-R/geoknife/blob/master/inst/extdata/state_webgeom_post.xml#L72
- [ ] https://github.com/USGS-R/geoknife/blob/master/man/webdata-methods.Rd#L46
- [ ] https://github.com/USGS-R/geoknife/blob/master/man/webgeom-methods.Rd#L75
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-dodsReplace.R#L5
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-dodsReplace.R#L9
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-download_result.R#L3
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-knife_shorthand.R#L14
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-webprocess_input.R#L40
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-webprocess_object.R#L5
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-webprocess_object.R#L13
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-webprocess_object.R#L15
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-webprocess_object.R#L16
- [x] https://github.com/USGS-R/geoknife/blob/master/tests/testthat/test-webprocess_object.R#L17
- [x] https://github.com/USGS-R/geoknife/blob/master/vignettes/geoknife.Rmd#L42
- [x] https://github.com/USGS-R/geoknife/blob/master/vignettes/geoknife.Rmd#L292
- [x] https://github.com/USGS-R/geoknife/blob/master/vignettes/geoknife.Rmd#L431
- [x] https://github.com/USGS-R/geoknife/blob/master/vignettes/geoknife.Rmd#L466
- [x] https://github.com/USGS-R/geoknife/blob/master/vignettes/geoknife.Rmd#L477
- [x] https://github.com/USGS-R/geoknife/blob/master/vignettes/geoknife.Rmd#L499
- [x] https://github.com/USGS-R/geoknife/blob/master/vignettes/geoknife.Rmd#L556
- [x] https://github.com/USGS-R/geoknife/blob/master/vignettes/geoknife.Rmd#L575

**Comment by jread-usgs** [comment]
Thanks @wdwatkins
