### ISSUE TITLE
method to coerce geojob into webdata object

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#327]

**Comment by wdwatkins** [comment]
Will this utilize #332?

**Comment by wdwatkins** [comment]
Where would the variables come from?  They aren't in the geojob xml right?

**Comment by jiwalker-usgs** [comment]
They are in the xml, the input is DATASET_ID

**Comment by wdwatkins** [comment]
What about when that isn't present?  Just leave it blank? 

https://cida.usgs.gov/gdp/process/request?id=c8c5d162-6db3-4074-bc85-772af418a22e

**Comment by jread-usgs** [comment]
@wdwatkins is this good to close with #334 ?

**Comment by wdwatkins** [comment]
Think so

**Comment by jread-usgs** [comment]
OK, I will take it for a spin and close this down if we are 👍
