### ISSUE TITLE
new url needed for daymet?

### ISSUE THREAD

**Issue by alatzka** [USGS-R/geoknife#339]
Looks like the url for webdata("daymet") needs to be updated for the new version of Daymet. I think the correct one should be: "http://thredds.daac.ornl.gov/thredds/dodsC/daymet-v3-agg/na.ncml"

OPeNDAP: http://thredds.daac.ornl.gov/thredds/dodsC/daymet-v3-agg/na.ncml.html

**Comment by jiwalker-usgs** [comment]
Thanks for letting us know about this change.  We'll incorporate this new url into the next release.

**Comment by JodiNorris** [comment]
The old "daymet" fabric in geoknife is no longer working, at least for me. I haven't figured out how to make the new URL work within geoknife, beyond getting it to recognize the daymet variables. It seems like a workaround should be possible using a custom setting but I haven't figured it out.

**Comment by jread-usgs** [comment]
@JodiNorris we'll look into this

**Comment by jread-usgs** [comment]
see #369

**Comment by JodiNorris** [comment]
Thanks!   
Although "daymet" still isn't working directly as an argument to webdata the way it used to (it will load as a fabric but has no variables), it's now possible to pull Daymet from the full webdata list. Eg to set the the continental US Daymet as a fabric :
`all_webdata <- query("webdata")`
`all_titles <- title(all_webdata)`
`whichDaymet_titles <- grep("daymet", ignore.case = TRUE, all_titles)`
`all_titles[whichDaymet_titles]`
`daymet_title <- all_titles[whichDaymet_titles[1]]`
`fabricDaymet <- webdata(all_webdata[daymet_title])`

**Comment by jread-usgs** [comment]
Hmmm...have you tried installing this development version?

```r
devtools::install_github('usgs-r/geoknife')

library(geoknife)
webdata('daymet')
An object of class "webdata":
times: 2000-01-01T00:00:00Z, 2001-01-01T00:00:00Z
url: https://thredds.daac.ornl.gov/thredds/dodsC/daymet-v3-agg/na.ncml 
variables: prcp
```

should to work w/ the queries too:
```r
query(webdata('daymet'), 'times')
[1] "1980-01-01 UTC" "2017-12-31 UTC"
```

**Comment by JodiNorris** [comment]
Thanks, I may try that soon;  for now I'll probably stick with specifying daymet the longer way so that the scripts will be compatible for other users in our office, and I'll update the script as needed.
 
We really appreciate geoknife and these datasets - especially the less common topoWX and the "United States Stage IV Quantitative Precipitation Archive"

**Comment by jread-usgs** [comment]
:+1:
