### ISSUE TITLE
fix broken checks as reported by CRAN

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#344]
https://cran.r-project.org/web/checks/check_results_geoknife.html

```
Version: 1.5.4 
Check: tests 
Result: ERROR 
     Running ‘testthat.R’ [3s/18s]
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
     6: getNodeSet(response, xpath, namespaces = namespaces)
     7: xpathApply(doc, path, fun, ..., namespaces = namespaces, sessionEncoding = sessionEncoding, 
     addFinalizer = addFinalizer)
     8: xpathApply.XMLInternalDocument(doc, path, fun, ..., namespaces = namespaces, sessionEncoding = sessionEncoding, 
     addFinalizer = addFinalizer)
     9: matchNamespaces(doc, namespaces)
     10: stop("cannot find defined namespace(s) with prefix(es) ", paste(namespaces[i][is.na(idx)], 
     collapse = ", "))
     
     testthat results ================================================================
     OK: 53 SKIPPED: 62 FAILED: 1
     1. Error: show datagroup (@test-show_object.R#23) 
     
     Error: testthat unit tests failed
     Execution halted 
Flavors: r-devel-linux-x86_64-debian-clang, r-devel-linux-x86_64-debian-gcc, r-release-linux-x86_64
```

**Comment by wdwatkins** [comment]
Haven't been able to reproduce this, either on OSX or on a linux VM with Ubuntu.  Kinda wonder if it is just a flaky internet issue when it goes to find the XML namespace definitions?  If there is a problem it is os-specific:
![image](https://cloud.githubusercontent.com/assets/13987349/26594639/032edf06-452e-11e7-97bd-1be079250e78.png)

There are however two warnings about deprecated functions that I will try to fix.  
@jiwalker-usgs @jread-usgs any other thoughts?

**Comment by wdwatkins** [comment]
Although I was working with the latest master version, maybe we changed something since the last CRAN release that fixed this.

**Comment by jread-usgs** [comment]
same for me ...

**Comment by jread-usgs** [comment]
@wdwatkins this is what is on CRAN: https://github.com/USGS-R/geoknife/releases/tag/v1.5.4

**Comment by jread-usgs** [comment]
or can do a CMD check w/ the downloaded source from CRAN

**Comment by wdwatkins** [comment]
Are we just missing things that need to be `skip_on_cran`?  The test that failed is just the basic webdata query.  Some of OSes have different errors, but are all on external features, shouldn't those be skipped?

**Comment by jread-usgs** [comment]
I guess so (for skip_on_cran()). Can you update those tests?

**Comment by wdwatkins** [comment]
Now on CRAN 6/6/17
