### ISSUE TITLE
make tests run faster

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/geoknife#359]
Let's collect ideas of how to make the tests run faster here then implement them. Quickly. 

The big one I see if making all the prism calls 1 time step by adjusting the end time.

**Comment by jiwalker-usgs** [comment]
We may also want to mock many of the remote calls as we want to test the package, not necessarily GDP.

**Comment by dblodgett-usgs** [comment]
For sure, the first one I want to mock is the process status! This was horrible to try and test. https://github.com/dblodgett-usgs/geoknife/blob/991da7a9ce4958c6ba4a2b752f00c0acb663c027/tests/testthat/test-geoknife_utils.R
