### ISSUE TITLE
cannot use `download` with a netcdf output

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/geoknife#367]
In the how-to-gdp viz, I've been manually downloading the netcdf output because there was no netcdf parser.

```
start_date <- "2008-06-12 22:00:00"
end_date <- "2008-06-12 22:00:00"
stencil <- geoknife::simplegeom(geom_sp)
fabric <- geoknife::webdata(url = 'https://cida.usgs.gov/thredds/dodsC/stageiv_combined', 
                            variables = "Total_precipitation_surface_1_Hour_Accumulation", 
                            times = c(start_date, end_date))
knife <- geoknife::webprocess("subset")
job <- geoknife::geoknife(stencil, fabric, knife, wait = TRUE, 
                          REQUIRE_FULL_COVERAGE=FALSE, 
                          OUTPUT_TYPE="netcdf")
```

```
## this throws an error:
geoknife::download(job, destination = "context_precip.nc")
retrying...
retrying...
retrying...
retrying...
Error: Must specify at least one of url or handle
```

```
# need to download manually since no netcdf parser
download.file(url = geoknife::check(job)$URL, 
              destfile = "context_precip.nc", 
              mode="wb")
```

**Comment by jread-usgs** [comment]
@lindsaycarr can you add `geom_sp` to the issue so we can reproduce the error?

**Comment by jread-usgs** [comment]
This didn't error for me
```r
geoknife::download(job, destination = "context_precip.nc")
[1] "context_precip.nc"
```

**Comment by wdwatkins** [comment]
Could this be due to not having the NetCDF C libraries installed?  Wouldn't expect that error message though.

**Comment by lindsaycarr** [comment]
Just tried this again, and I don't get an error. We had an entire conversation about this on Slack though and I thought others were getting that error. Maybe it was a network issue on that day?

Attached the `geom_sp` file for posterity (had to be zip because rds is not supported).

[geom_sp.zip](https://github.com/USGS-R/geoknife/files/1716762/geom_sp.zip)

**Comment by jread-usgs** [comment]
Can't reproduce this error, so am assuming it is a blip. re-open if you see it again.
