### ISSUE TITLE
"General Error: ucar.ma2.InvalidRangeException: Grid doesn't cover bounding box."

### ISSUE THREAD

**Issue by lisefiore** [USGS-R/geoknife#368]
I am trying to collect climate data from MACA (output:geotiff). My code works for all the states I want excepted for Florida. I got the message error:  "General Error: ucar.ma2.InvalidRangeException: Grid doesn't cover bounding box."

Below a portion of my code: 
stencil <-webgeom('state:: Texas, Mississippi, Alabama, Florida, Georgia, South Carolina, North Carolina')
job <- geoknife(stencil, fabric, knife, wait = TRUE, OUTPUT_TYPE = "geotiff")

**Comment by jread-usgs** [comment]
here is a full working example:
```r
library(geoknife)
fabric <- webdata('url' = "dods://cida.usgs.gov/thredds/dodsC/macav2metdata_monthly_future", 
                  variables = "was_MIROC5_r1i1p1_rcp85",
                  times = c("2005-12-31T00:00:00.000Z", "2005-12-31T00:00:00.000Z"))

stencil <- webgeom('state::Texas,Mississippi,Florida,Alabama,Georgia,South Carolina,North Carolina')

job <- geoknife(stencil, fabric, knife = 'subset', wait = TRUE, OUTPUT_TYPE = "geotiff", REQUIRE_FULL_COVERAGE = FALSE)
```
Note the 
```r
REQUIRE_FULL_COVERAGE = FALSE
```

I am assuming part of FL (islands?) isn't covered by the dataset. the default is to fail unless the user overrides and says it is ok if the dataset (`fabric`) doesn't fully cover the `stencil`.
