### ISSUE TITLE
Update disclaimer

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/geoknife#371]
https://www2.usgs.gov/fsp/fsp_disclaimers.asp#5

"This software has been approved for release by the U.S. Geological Survey (USGS). Although the software has been subjected to rigorous review, the USGS reserves the right to update the software as needed pursuant to further analysis and review. No warranty, expressed or implied, is made by the USGS or the U.S. Government as to the functionality of the software and related material nor shall the fact of release constitute any such warranty. Furthermore, the software is released on condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from its authorized or unauthorized use."

On code.usgs.gov, this is being required for public repositories in a "DISCLAIMER.md" file.

**Comment by wdwatkins** [comment]
Was added in https://github.com/USGS-R/geoknife/commit/f093feb2c50e0615b28eab20d7ec35c6a9ba6bc2
