### ISSUE TITLE
Gages II as a webgeom

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/geoknife#381]
```r
library(geoknife)
fabric <- webdata("prism")
stencil <- webgeom(url = "https://cida.usgs.gov/nwc/geoserver/NWC/ows", 
                   geom = "NWC:gagesii_basins", attribute = "gage_id")
values(stencil) <- "01013500"
wp <- webprocess(REQUIRE_FULL_COVERAGE = "false")
job <- geoknife(stencil, fabric, wp, wait = TRUE)
intersected <- result(job)
plot(intersected$DateTime, intersected$`01013500`)
```

**Comment by Flash-Of-Thunder** [comment]
"https://cida.usgs.gov/nwc/geoserver/NWC/ows" "This website, the NWC-DP, has been deprecated as of September 1, 2020. All data accessible through the NWC-DP are also available on NWISWeb (https://waterdata.usgs.gov/) and will remain so in perpetuity. This website now redirects to NWISWeb. Please direct any questions about this web application shutdown to gs-w-iow_po_team@usgs.gov." 

Hmm so what's the new URL to get the stencil? If I find it I'll post here.

**Comment by Flash-Of-Thunder** [comment]
I found a zip file of the boundaries but I'm not sure that's the solution: https://water.usgs.gov/GIS/dsdl/boundaries_shapefiles_by_aggeco.zip

**Comment by dblodgett-usgs** [comment]
Hi @Flash-Of-Thunder -- Many of the layers on the geoserver in question moved here. https://labs.waterdata.usgs.gov/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?1&filter=false

That gagesii basins layer did not. 

You could use the shapefile you found, depending on your use case. Can you describe more of what you are trying to do? I can probably help with a work around.

I'll also ask about posting that basin boundary set to the new geoserver. I can think of a few applications for it now.

**Comment by Flash-Of-Thunder** [comment]
Wow swift response. My goal is to pull averaged daymet data (e.g. prcp, tmax, tmin) for specific basins. E.g. the daily time series of prcp for "01013500". I was using a python package, pydaymet, for this but it was taking an exceptionally long time for multiple basins and I was wondering if I'd have more success with this R tool.

**Comment by Flash-Of-Thunder** [comment]
Is it possible to use an existing polygon as a stencil. As there is this tool: https://usgs-r.github.io/nhdplusTools/reference/get_nldi_basin.html

Or perhaps I look to see where they are pulling this from?

**Comment by dblodgett-usgs** [comment]
Yeah --- that is one way to get a basin boundary. 

You would convert that into a simplegeom. 

Something like this:
```r
sites <- c("USGS-08279500", "USGS-06287800")

basins <- lapply(sites, function(x){
  nhdplusTools::get_nldi_basin(list(featureSource = "nwissite",
                                    featureID = x))
})

basins <- geoknife::simplegeom(do.call(rbind, basins))
```
Probably best to group these spatially for passing along to the GDP. e.g. if you need basins spread out all over the place (but clusters) run them through the GDP in the clusters.

**Comment by Flash-Of-Thunder** [comment]
Thanks! I see that the function did pull the polygon but saved it as an "sf" object

> basins <- simplegeom(do.call(rbind, basins))
Error in as(.Object, "simplegeom") : 
  no method or default for coercing “sf” to “simplegeom”

![image](https://user-images.githubusercontent.com/94713715/150085084-0db7d3e2-5cec-4fc3-ac04-baa655f8d9d3.png)

**Comment by dblodgett-usgs** [comment]
Please try the latest version of geoknife. `remotes::install_github("usgs-r/geoknife")`

**Comment by Flash-Of-Thunder** [comment]
Brilliant! It works, but webdata("daymet") is now producing an error. I was able to pull prism data using the following code: 

```
install.packages("remotes")
remotes::install_github("usgs-r/geoknife")
install.packages("nhdplusTools")

library("geoknife")
library("nhdplusTools")

sites <- c("USGS-08279500", "USGS-06287800")

basins <- lapply(sites, function(x){
  nhdplusTools::get_nldi_basin(list(featureSource = "nwissite",
                                    featureID = x))
})

stencil <- simplegeom(do.call(rbind, basins))
fabric <- webdata("prism")
times(fabric) <- as.POSIXct(c('2003-01-01','2005-01-01'))
job <- geoknife(stencil, fabric, wait = TRUE)
```

But when I changed "prism" to "daymet" I got the following error:
`
General Error: java.io.IOException: java.io.IOException: opendap.dap.DAP2Exception: opendap.dap.DAP2Exception: Not a valid OPeNDAP server - Missing MIME Header fields! Either "XDAP" or "XDODS-Server." must be present
`

The issue is mentioned in #339 but I can't tell if it's the same bug.

**Comment by dblodgett-usgs** [comment]
OK, the URL in code is actually wrong for daymet. 

If you do 
`url(fabric) <- "https://thredds.daac.ornl.gov/thredds-daymet/dodsC/daymet-v3-agg/na.ncml" `

And try again, it will work. I'll get that url fixed in source.

**Comment by dblodgett-usgs** [comment]
The latest from github should now work?
