### ISSUE TITLE
Seeing `url` issues in `webprocess()`

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#383]
I don't think we've changed anything here, but code is now breaking because the default url in `webprocess()` is `utility` instead of instead of `process`

Goes to `GET /gdp/utility/WebProcessingService?service=WPS&version=1.0.0&request=DescribeProcess&identifier=gov.usgs.cida.gdp.wps.algorithm.FeatureWeightedGridStatisticsAlgorithm` and fails w/

```
Error in checkException(doc) : 
  Algorithm does not exist: gov.usgs.cida.gdp.wps.algorithm.FeatureCoverageOPeNDAPIntersectionAlgorithm
```

**Comment by dblodgett-usgs** [comment]
Looking into this, I don't think this is an issue any more? 

UTILITY_URL is set here: https://github.com/USGS-R/geoknife/blob/master/R/04-webprocess-obj.R#L84
 and, AFAICT, not used in the webprocess initialization. 

Reopen if you think I'm missing something...
