### ISSUE TITLE
NOTICE: upcoming default branch name change

### ISSUE THREAD

**Issue by jesse-ross** [USGS-R/geoknife#408]
The `master` branch of this repository will soon be renamed from `master` to `main`, as part of a coordinated change across the USGS-R and USGS-VIZLAB organizations.  This is part of a broader effort across the git community to use more inclusive language. For instance, [git](https://sfconservancy.org/news/2020/jun/23/gitbranchname/), [GitHub](https://github.com/github/renaming), and [GitLab](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/) have all changed or are in the process of changing their default branch name.

We will make this change early in the week of February 6, 2022. The purpose of this issue is to give notification of the change and provide information on how to make it go smoothly.

If you wish to make the change yourself rather than wait for us to do it, it can either be done manually or through some convenience functions in the `usethis` package.

- [ ] From your local version of the repository, change the remote branch name using either of the methods detailed below: `usethis` or the manual method.
- [ ] Verify that the local branches are changed as well (if using `usethis`) or change them yourselves (if using the manual method).
- [ ] If you have collaborators on this repository, let them know that they will need to change their forked/local repos either by running `usethis::git_default_branch_rediscover()` or by steps 2 and 3 of the manual method. Point them to this issue to facilitate the process!
- [ ] Search within your repository for "master" so that you can change references (e.g. URLs pointing to specific commit points of files) to point to "main" instead.
- [ ] When you are done, feel free to close this issue!

### Using usethis
**Note: `usethis` must be version 2.1.2 or higher**

1. Navigate to your project's working directory.
1. Double-check that you have git credentials set up for HTTPS by running `usethis::gh_token_help()`. If you have not yet set up git credentials for HTTPS, you can do so by [creating a GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and using `gitcreds::gitcreds_set()` to register it with git. The PAT must have at least "repo" scope. ![gitcreds_gitcreds_set](https://user-images.githubusercontent.com/13890601/145628670-8d8caf1e-b3e4-4152-b3cf-0f3028481290.png)
1. Rename default branches locally and on all remote repositories at once with `usethis::git_default_branch_rename()`. For more details see [here](https://usethis.r-lib.org/reference/git-default-branch.html).<br/> ![](https://user-images.githubusercontent.com/13890601/144508471-d2cf8b38-b686-4c7d-ba77-2f5ca2d8adec.png) 
1. Verify that the work was successful by running `usethis::git_default_branch()`.

### Manual Method
1. Go to \<your repository\> -> Settings -> Branches and edit the default branch from `master` to `main`.
1. All members should update their local settings so that new repositories created locally will have the correct default branch: `git config --global init.defaultBranch main`.
1. All members must update their local settings to match the change to this repository. They can either do this with `usethis::git_default_branch_rediscover()` (see above) or else run the following:
```r
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by jread-usgs** [comment]
I think this was already done on this repo?

![image](https://user-images.githubusercontent.com/2349007/150413266-68aef4f5-82d7-4e9c-bbb8-7ec8ab62e6ac.png)

**Comment by dblodgett-usgs** [comment]
Yep -- I took care of it, thought I'd closed the ticket.
