### ISSUE TITLE
create GDP output parser

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#50]
to `data.frame`

**Comment by jread-usgs** [comment]
upvote :+1:

**Comment by jiwalker-usgs** [comment]
I think it would be cool if GDP put out a more standard format first of all, but either way this is cool :+1:

**Comment by lawinslow** [comment]
There's some code we could start with from [mda.lakes](https://github.com/USGS-R/mda.lakes/blob/master/R/load_gdp_file.R).

**Comment by jread-usgs** [comment]
Advice on how to do this? I was thinking of having the input be the processID URI, for example http://cida.usgs.gov/gdp/process/RetrieveResultServlet?id=8c060a5e-381b-44ef-a13b-277ed2303c6f

from that I could get the output type (e.g., `text/tab-separated-values`) and the file location to pull it in. Could also figure out if there are a) multiple variables, and b) multiple features, which make the parsing a little trickier. 
Thoughts? @lawinslow @jiwalker-usgs

**Comment by jread-usgs** [comment]
or, point to the local file, or point to the file location URI. 

is this `loadOutput()`?

**Comment by lawinslow** [comment]
You could be endpoint agnostic, like `read.table` and the like. Point to a file, it loads it. Point to http://XXX, it downloads and loads it.

**Comment by jread-usgs** [comment]
ok, but how does it know what parser to use? Could be .nc or csv or tsv or geotiff etc.

**Comment by lawinslow** [comment]
same issue on the filesystem as on the web, right? Or are you reading metadata from the job to determine format? 

Could use a type argument. Or different functions for different formats (not a terrible idea as having one function output an unpredictable object structure is not super easy to deal with, so at some level in your processing, you'll probably know or assume the format).

**Comment by jread-usgs** [comment]
Yeah, I was thinking there would be a handful of supported parsers, but that the handling of which one to use would not require user input. Hence using the info in the processID or something similar. 

Pointing to the file definitely makes more sense, it just requires a bit more work for the user. ...hmmm

**Comment by jread-usgs** [comment]
For the user, two extremes (for options) would be:
```R
loadOutput(geoknife)
```
or
```R
loadOutput(file = X, type = Y, etc....)
```

The first option also may result in some head-scratching, because it could return a list or a data.frame or something else depending on the GDP result.

**Comment by jiwalker-usgs** [comment]
The output should be identifiable by the Content-Type header or the MimeType in the response document, so loadOutput can branch based on that.  Right now the options are text/csv, text/tab-separated-values, or text/plain for tabular output.  For gridded output the options are application/geotiff or application/x-geotiff and application/netcdf or application/x-netcdf.

**Comment by jread-usgs** [comment]
yep, so using the processID

**Comment by jread-usgs** [comment]
@jiwalker-usgs what is "text/plain" an output for? like doing dominant landcover fractions? that type of output?

**Comment by jiwalker-usgs** [comment]
text/plain is the mimeType for space delimited tabular output.

**Comment by jread-usgs** [comment]
hmm..if I specify DELIMITER=SPACE, it is returned as mimType = text/csv

**Comment by jread-usgs** [comment]
@jiwalker-usgs do I get to report a bug? :clap:

**Comment by jiwalker-usgs** [comment]
Yeah, I think that is a bug.  Or should we call it a feature?

--
Jordan Walker
Center for Integrated Data Analytics
US Geological Survey
8505 Research Way
Middleton, WI 53562
608.821.3842
http://cida.usgs.gov

**Comment by jread-usgs** [comment]
I bugged it. Or featured it. over on https://github.com/USGS-CIDA/geo-data-portal

**Comment by jread-usgs** [comment]
#60
