### ISSUE TITLE
create .nc DSG output parser

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#51]
per @dblodgett-usgs request

**Comment by jread-usgs** [comment]
@dblodgett-usgs , so this parses _into_ DSG, as opposed to _reads_ DSG as a new output type from GDP? just clarifying.

**Comment by dblodgett-usgs** [comment]
Yes. This parses into DSG so data can be used later in tools like the THREDDS Data Server.

**Comment by jread-usgs** [comment]
this exists over in https://github.com/USGS-R/netcdf.dsg
