### ISSUE TITLE
GDP output parser for complex timeseries returns

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#61]
- [x] multiple stats
- [x] multiple vars
- [x] multiple stats and vars
- [x] example output for all of the above for testing

**Comment by jread-usgs** [comment]
forgot that stats add columns. Vars add blocks:
![image](https://cloud.githubusercontent.com/assets/2349007/6096696/6bd0b1c0-af66-11e4-8a8c-d144a12ac45e.png)

**Comment by jread-usgs** [comment]
initial look into `fread` and other handiness in `data.table` makes me think it may be worth bringing in that package to deal with these goofy files.

**Comment by lawinslow** [comment]
If it helps go for it. It's got good functionality. You could pretty easily just as.data.frame() it before outputting (or really even using) it.

**Comment by jread-usgs** [comment]
yeah, was going to use the `fread(data.table = FALSE)`, which would then return a d.f

I might be able to get away with read.table w/ the same trickery though...looking into that.

**Comment by jread-usgs** [comment]
This gets me everything I need to know about reading the chunks of the file:
```R
parseConfig = function(file, delim){
  statLine = 3
  featureLine = 2
  skipHead = 1
  varMarker = '# '
  c <- file(file,"r") 
  fileLines <- readLines(c)
  close(c)
  nRead <- length(fileLines)
  blockStart <- grep(varMarker, fileLines)
  skips = blockStart+skipHead
  blockEnd = c(blockStart[-1] - 1, nRead)
  nrows = blockEnd - skips
  stats = unique(strsplit(fileLines[statLine], split = delim)[[1]][-1])
  features = unique(strsplit(fileLines[featureLine], split = delim)[[1]][-1])
  vars = sub(varMarker,"",fileLines[blockStart])
  config = list(vars = vars, stats = stats, features = features, skip = skips, nrows = nrows)
  return(config)
}
```

**Comment by jread-usgs** [comment]
instead of generating a funky list, I am leaning on leveraging sorting and subsetting of data.frame, and generate output as a simple data.frame that looks more like this:
![image](https://cloud.githubusercontent.com/assets/2349007/6097270/46f1e95c-af7d-11e4-8595-ebd4802a4dc2.png)

**Comment by lawinslow** [comment]
Ugh, if that file format ever changes, that parser is boned. 

Up vote for actual data.frame output instead of list.

**Comment by jread-usgs** [comment]
would love for the stat and units concept to not be combined. 

I.e., this job would be a lot easier if this was the format:
```
# prcip (mm/d)
bla bla
TIMESTEP MEAN MEAN MEAN
```
since the units are different for the different variables and I want to sort based on the statistic, not the (likely) unique stat+units header
